### ISSUE TITLE
Console theme/create report error

### ISSUE THREAD

**Issue by helprepair** [luyadev/luya-kickstarter-bootstrap4#19]
### What steps will reproduce the problem?

php luya theme/create

### What is the expected result?
$ php luya theme/create
Enter the name (lower case) of the theme you like to generate: basic
Enter the theme location where to generate (as path alias e.g. app, ): [app]
@app\themes\basicPHP Warning 'yii\base\ErrorException' with message 'preg_replace(): Delimiter must not be alphanum
eric or backslash'

in D:\app\day01\example0001\1.2.3\vendor\luyadev\luya-core\console\commands\ThemeController.php:64

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'preg_replace():...', 'D:\\app\\day01\\ex...', 64, Ar
ray)
#1 D:\app\day01\example0001\1.2.3\vendor\luyadev\luya-core\console\commands\ThemeController.php(64): preg_replace('
\\', '/', '@app\\themes\\bas...')
#2 [internal function]: luya\console\commands\ThemeController->actionCreate('basic')
#3 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#4 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParam
s(Array)
#5 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\console\Controller.php(182): yii\base\Controller->runAction('
create', Array)
#6 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\base\Module.php(552): yii\console\Controller->runAction('crea
te', Array)
#7 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('the
me/create', Array)
#8 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAct
ion('theme/create', Array)
#9 D:\app\day01\example0001\1.2.3\vendor\yiisoft\yii2\base\Application.php(384): yii\console\Application->handleReq
uest(Object(yii\console\Request))
#10 D:\app\day01\example0001\1.2.3\vendor\luyadev\luya-core\base\Boot.php(238): yii\base\Application->run()
#11 D:\app\day01\example0001\1.2.3\vendor\luyadev\luya-core\bin\luya(36): luya\base\Boot->applicationConsole()
#12 {main}

### What do you get instead? (A Screenshot can help us a lot!)

![图片](https://user-images.githubusercontent.com/105917325/177097613-cf928e4a-cae9-4b82-9897-2ba0a2106010.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.2.3
| PHP Version      | 7.4.28
| Platform         | WNMP
| Operating system | Windows 10

**Comment by nadar** [comment]
@boehsermoe maybe you know something regarding this?

**Comment by helprepair** [comment]
> 
luyadev\luya-core\console\commands\ThemeController.php

```
        // $basePath = $themeLocation . DIRECTORY_SEPARATOR . 'themes' . DIRECTORY_SEPARATOR . $themeName;
        $basePath = $themeLocation . '/' . 'themes' . '/' . $themeName; // fix
        $themeFolder = Yii::getAlias($basePath);
```
After I make this modification, I can create it successfully.

**Comment by nadar** [comment]
But you mentioned you are on windows, so it should be `\` not `/`. But i think its because Yii::getAlias throws an exception here: https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L154 

@helprepair could you provide me the value of $themeLocation and $basePath before and after running Yii::getAlias?
