### ISSUE TITLE
luya import error

### ISSUE THREAD

**Issue by neoacevedo** [luyadev/luya-kickstarter-bootstrap4#35]
### What steps will reproduce the problem?

After install via composer create-project and running the migration, I ran the command `vendor/bin/luya import`.

### What is the expected result?

Run the import successfully.

### What do you get instead? (A Screenshot can help us a lot!)
```
~# ./vendor/bin/luya import

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of luya\cms\base\InternalBaseBlock::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php:124
Stack trace:
#0 /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php(25): yii\base\ErrorHandler->handleError(8192, 'Return type of ...', '/app/vendor/luy...', 124)
#1 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#2 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#3 /app/vendor/luyadev/luya-module-cms/src/base/PhpBlock.php(17): Composer\Autoload\ClassLoader->loadClass('luya\\cms\\base\\I...')
#4 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#5 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#6 /app/vendor/luyadev/luya-module-cms/src/frontend/blocks/HtmlBlock.php(15): Composer\Autoload\ClassLoader->loadClass('luya\\cms\\base\\P...')
#7 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#8 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#9 [internal function]: Composer\Autoload\ClassLoader->loadClass('luya\\cms\\fronte...')
#10 /app/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('\\luya\\cms\\front...')
#11 /app/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('\\luya\\cms\\front...')
#12 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('\\luya\\cms\\front...', Array, Array)
#13 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('\\luya\\cms\\front...', Array, Array)
#14 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(263): yii\BaseYii::createObject(Array)
#15 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(202): luya\cms\admin\importers\BlockImporter->createBlockObject('\\luya\\cms\\front...')
#16 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(40): luya\cms\admin\importers\BlockImporter->saveBlock('\\luya\\cms\\front...')
#17 /app/vendor/luyadev/luya-core/console/commands/ImportController.php(192): luya\cms\admin\importers\BlockImporter->run()
#18 [internal function]: luya\console\commands\ImportController->actionIndex()
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
#22 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#23 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('import', Array)
#24 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('import', Array)
#25 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /app/vendor/luyadev/luya-core/base/Boot.php(238): yii\base\Application->run()
#27 /app/vendor/luyadev/luya-core/bin/luya(36): luya\base\Boot->applicationConsole()
#28 /app/vendor/bin/luya(119): include('/app/vendor/luy...')
#29 {main} in /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php on line 25
PHP Fatal Error 'yii\base\ErrorException' with message 'During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of luya\cms\base\InternalBaseBlock::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php:124
Stack trace:
#0 /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php(25): yii\base\ErrorHandler->handleError(8192, 'Return type of ...', '/app/vendor/luy...', 124)
#1 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#2 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#3 /app/vendor/luyadev/luya-module-cms/src/base/PhpBlock.php(17): Composer\Autoload\ClassLoader->loadClass('luya\\cms\\base\\I...')
#4 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#5 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#6 /app/vendor/luyadev/luya-module-cms/src/frontend/blocks/HtmlBlock.php(15): Composer\Autoload\ClassLoader->loadClass('luya\\cms\\base\\P...')
#7 /app/vendor/composer/ClassLoader.php(576): include('/app/vendor/luy...')
#8 /app/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/app/vendor/com...')
#9 [internal function]: Composer\Autoload\ClassLoader->loadClass('luya\\cms\\fronte...')
#10 /app/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('\\luya\\cms\\front...')
#11 /app/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('\\luya\\cms\\front...')
#12 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('\\luya\\cms\\front...', Array, Array)
#13 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('\\luya\\cms\\front...', Array, Array)
#14 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(263): yii\BaseYii::createObject(Array)
#15 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(202): luya\cms\admin\importers\BlockImporter->createBlockObject('\\luya\\cms\\front...')
#16 /app/vendor/luyadev/luya-module-cms/src/admin/importers/BlockImporter.php(40): luya\cms\admin\importers\BlockImporter->saveBlock('\\luya\\cms\\front...')
#17 /app/vendor/luyadev/luya-core/console/commands/ImportController.php(192): luya\cms\admin\importers\BlockImporter->run()
#18 [internal function]: luya\console\commands\ImportController->actionIndex()
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
#22 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#23 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('import', Array)
#24 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('import', Array)
#25 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /app/vendor/luyadev/luya-core/base/Boot.php(238): yii\base\Application->run()
#27 /app/vendor/luyadev/luya-core/bin/luya(36): luya\base\Boot->applicationConsole()
#28 /app/vendor/bin/luya(119): include('/app/vendor/luy...')
#29 {main}'

in /app/vendor/luyadev/luya-module-cms/src/base/InternalBaseBlock.php:25

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

It can't be executed.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 2.3(?)
| PHP Version      | 8.2
| Platform         | nginx+php-fpm.
| Operating system | Linux (docker).

**Comment by nadar** [comment]
what does your composer.json look like? because this should be fixed, see https://github.com/luyadev/luya-module-cms/blob/master/src/base/InternalBaseBlock.php#L125

ensure to have the lastest luya cms version in your composer.json constraint!

**Comment by nadar** [comment]
sth like `^5.1`

**Comment by neoacevedo** [comment]
I had to run a composer update.
The composer.json is the same at https://github.com/luyadev/luya-module-admin/issues/761#issuecomment-2081190223

**Comment by nadar** [comment]
so not its fixed? cms should be `^5.0` not `4.0. also for the admin it should be `^5.0` not 4.0

**Comment by neoacevedo** [comment]
Then it should be changed at L7 and L8 in the kickstarter bs4 composer file:
https://github.com/luyadev/luya-kickstarter-bootstrap4/blob/master/composer.json#L7
https://github.com/luyadev/luya-kickstarter-bootstrap4/blob/master/composer.json#L8

**Comment by nadar** [comment]
you are right; i have adjusted the kickstarter
